# fly.toml app configuration file generated for amacss-bot on 2024-10-14T21:10:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'amacss-bot'
primary_region = 'yyz'

[mounts]
  source = "amacss_bot"
  destination = "/data"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
